global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using PuppyApp.UnoApp.Models;
global using PuppyApp.UnoApp.Presentation;
global using PuppyApp.UnoApp.DataContracts;
global using PuppyApp.UnoApp.DataContracts.Serialization;
global using PuppyApp.UnoApp.Services.Caching;
global using PuppyApp.UnoApp.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using Color = Windows.UI.Color;